import Head from 'next/head'
import { ResponsivePie } from '@nivo/pie'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'

export default function Home() {
  const [courseData, setCourseData] = useState([])
  const [loading, setLoading] = useState(false)
  useEffect(() => {
    (async () => {
      const url = `${process.env.NEXT_PUBLIC_BACKEND_URL}/courses/all`

      setLoading(prev => !prev)

      const response = await fetch(url)
      const data = await response.json()

      if (data.data.length > 0) {
        setLoading(prev => !prev)
        setCourseData(data.data)
        console.log(data.data)
      }
    })()
  }, [])
  
  const fills = courseData.map((data) => {
    return {
      match: {
        id: data.id
      },
      id: 'dots'
    }
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Nivo Chart Example
        </h1>
        <p>
          Displaying courses and their number of available bursaries.
        </p>
          {
            loading ? <>
              Loading...
            </> : <div style={{
              width: "100vw",
              height: "80vh"
            }}>
            <ResponsivePie
        data={courseData}
        margin={{ top: 40, right: 80, bottom: 80, left: 80 }}
        innerRadius={0.5}
        padAngle={0.7}
        cornerRadius={3}
        activeOuterRadiusOffset={8}
        borderWidth={1}
        borderColor={{
            from: 'color',
            modifiers: [
                [
                    'darker',
                    0.2
                ]
            ]
        }}
        arcLinkLabelsSkipAngle={10}
        arcLinkLabelsTextColor="#333333"
        arcLinkLabelsThickness={2}
        arcLinkLabelsColor={{ from: 'color' }}
        arcLabelsSkipAngle={10}
        arcLabelsTextColor={{
            from: 'color',
            modifiers: [
                [
                    'darker',
                    2
                ]
            ]
        }}
        defs={[
            {
                id: 'dots',
                type: 'patternDots',
                background: 'inherit',
                color: 'rgba(255, 255, 255, 0.3)',
                size: 4,
                padding: 1,
                stagger: true
            },
            {
                id: 'lines',
                type: 'patternLines',
                background: 'inherit',
                color: 'rgba(255, 255, 255, 0.3)',
                rotation: -45,
                lineWidth: 6,
                spacing: 10
            }
        ]}
        fill={fills}
        legends={[
            {
                anchor: 'bottom',
                direction: 'row',
                justify: false,
                translateX: 0,
                translateY: 56,
                itemsSpacing: 0,
                itemWidth: 100,
                itemHeight: 18,
                itemTextColor: '#999',
                itemDirection: 'left-to-right',
                itemOpacity: 1,
                symbolSize: 18,
                symbolShape: 'circle',
                effects: [
                    {
                        on: 'hover',
                        style: {
                            itemTextColor: '#000'
                        }
                    }
                ]
            }
        ]}
    />
            </div>
          }
      </main>
    </div>
  )
}
